[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
upload_port = COM10
monitor_port = COM10
monitor_speed = 115200
lib_extra_dirs = C:/Users/01034/Documents/Arduino/libraries
